### ISSUE TITLE
Find an adequate chatroom where we may exchange info on the working process

### ISSUE THREAD

**Issue by rasundsbak** [rasundsbak/zoterokurs#26]
reading now
https://www.freecodecamp.org/news/how-to-secure-private-group-chat/
but no solution...

**Comment by Rasundsbak** [comment]
Suggested, but not yet tested:
https://www.leapchat.org/#KamikazeArsonistUnopenedReceiptFloristSuffocateMammalVulnerableBottleUnwrinkledSenatorBasketMortuaryNuclearPharmacySushiRustproofEggnogRobeNapkinRustproofAntelopeAbbreviateBananaHappiness
